void handleRoot() {
  String htmlContent = "<!DOCTYPE html>"
                       "<html lang='en'>"
                       "<head>"
                       "<meta charset='UTF-8'>"
                       "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                       "<title>Content Box Example</title>"
                       "<style>"
                       "body {"
                       "    background-color: #f0f0f0;"
                       "    font-family: Arial, sans-serif;"
                       "}"
                       ".cover {"
                       "    max-width: 500px;"
                       "    height: 500px;"
                       "    background-color: rgb(174, 174, 174);"
                       "    border-radius: 20px;"
                       "    box-shadow: 0 0 10px rgba(88, 87, 87, 0.3);"
                       "    margin: auto;"
                       "    overflow: auto;"
                       "}"
                       ".container {"
                       "    max-width: 80%;"
                       "    margin: 20px auto;"
                       "    text-align: center;"
                       "    overflow: auto;"
                       "}"
                       ".content-box {"
                       "    background-color: #ffffff;"
                       "    border-radius: 10px;"
                       "    padding: 20px;"
                       "    box-shadow: 0 0 10px rgba(88, 87, 87, 0.3);"
                       "    max-width: 600px;"
                       "    margin: 20px auto;"
                       "    height: 200px;"
                       "    overflow: auto;"
                       "}"
                       ".content-box p {"
                       "    line-height: 1.6;"
                       "}"
                       "</style>"
                       "</head>"
                       "<body>"
                       "<div class='cover'>"
                       "    <div class='container'>"
                       "        <h2>This is a Content Box</h2>"
                       "        <div class='content-box'>"
                       "            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>"
                       "        </div>"
                       "    </div>"
                       "</div>"
                       "</body>"
                       "</html>";
  server.send(200, "text/html", htmlContent);
}